### ISSUE TITLE
Doesn't recognize commands, and no formating on ANY output.

### ISSUE THREAD

**Issue by aknight2015** [LordFckHelmchen/WrathAndGloryXPOptimizer#8]
I type:

'python xpOptimizer.py --tier 1 --Strength 3 --MaxWounds 5 --return_json`

I get:

sage: xpOptimizer.py [-h] [-f FILE] [-j] [-v] [--Tier {1,2,3,4,5}] [--Strength {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Toughness {1,2,3,4,5,6,7,8,9,10,11,12}] [--Agility {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Initiative {1,2,3,4,5,6,7,8,9,10,11,12}] [--Willpower {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Intellect {1,2,3,4,5,6,7,8,9,10,11,12}] [--Fellowship {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Athletics {0,1,2,3,4,5,6,7,8}] [--Awareness {0,1,2,3,4,5,6,7,8}]
                      [--BallisticSkill {0,1,2,3,4,5,6,7,8}] [--Cunning {0,1,2,3,4,5,6,7,8}]
                      [--Deception {0,1,2,3,4,5,6,7,8}] [--Insight {0,1,2,3,4,5,6,7,8}]
                      [--Intimidation {0,1,2,3,4,5,6,7,8}] [--Investigation {0,1,2,3,4,5,6,7,8}]
                      [--Leadership {0,1,2,3,4,5,6,7,8}] [--Medicae {0,1,2,3,4,5,6,7,8}]
                      [--Persuasion {0,1,2,3,4,5,6,7,8}] [--Pilot {0,1,2,3,4,5,6,7,8}]
                      [--PsychicMastery {0,1,2,3,4,5,6,7,8}] [--Scholar {0,1,2,3,4,5,6,7,8}]
                      [--Stealth {0,1,2,3,4,5,6,7,8}] [--Survival {0,1,2,3,4,5,6,7,8}] [--Tech {0,1,2,3,4,5,6,7,8}]
                      [--WeaponSkill {0,1,2,3,4,5,6,7,8}] [--Conviction {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Defence {0,1,2,3,4,5,6,7,8,9,10,11}] [--Determination {1,2,3,4,5,6,7,8,9,10,11,12}]
                      [--Influence {0,1,2,3,4,5,6,7,8,9,10,11}] [--MaxShock {2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17}]
                      [--MaxWounds {3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}]
                      [--Resilience {2,3,4,5,6,7,8,9,10,11,12,13}] [--Resolve {0,1,2,3,4,5,6,7,8,9,10,11}]
xpOptimizer.py: error: unrecognized arguments: --tier 1

I'm running on Debian CLI.

**Comment by LordFckHelmchen** [comment]
Hey @aknight2015,

thanks for posting. The CLI is case-sensitive. Your 'tier' parameter is lower case - but upper case is expected. Changing this should fix things. 
Please close the issue if it does ;-)
Cheers!

**Comment by aknight2015** [comment]
Yeah. It does. I noticed that when I read the help file that was
printed out in the command line. In your guide though it's lowercase.
Easy oops.

**Comment by LordFckHelmchen** [comment]
A thanks for pointing it out. Fixed in f9418d0234e46bdf468fb02832aee1daacdcab07
